In [1]:
import numpy as np

In [2]:
np.array([4,3,65,78,1])

array([ 4,  3, 65, 78,  1])

In [3]:
np.array([3,2,7,9,5.4])

array([3. , 2. , 7. , 9. , 5.4])

In [4]:
np.array([3,2,7,9,5.4,'4'])

array(['3', '2', '7', '9', '5.4', '4'], dtype='<U32')

In [5]:
np.array([3,2,7,9,5.4,True])

array([3. , 2. , 7. , 9. , 5.4, 1. ])

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
# linspace - linear space
# it will generate 50 elements in that range with equal interval
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [10]:
np.linspace(1,20, num=25, retstep=True)

(array([ 1.        ,  1.79166667,  2.58333333,  3.375     ,  4.16666667,
         4.95833333,  5.75      ,  6.54166667,  7.33333333,  8.125     ,
         8.91666667,  9.70833333, 10.5       , 11.29166667, 12.08333333,
        12.875     , 13.66666667, 14.45833333, 15.25      , 16.04166667,
        16.83333333, 17.625     , 18.41666667, 19.20833333, 20.        ]),
 0.7916666666666666)

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.ones((3,4), dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
# will generate a random number b/w 0 and 1
np.random.random()

0.11545992414965656

In [23]:
np.random.random(10)

array([0.15282216, 0.57158836, 0.44790419, 0.51391708, 0.96849675,
       0.56866643, 0.7857207 , 0.05907881, 0.86642625, 0.58628617])

In [24]:
np.random.random((4,5))

array([[0.54455889, 0.9648364 , 0.42781475, 0.51704863, 0.92907419],
       [0.64416369, 0.49622088, 0.45565191, 0.33641145, 0.37890478],
       [0.30644384, 0.00790359, 0.64308142, 0.69353296, 0.53016405],
       [0.97966929, 0.18739322, 0.08286385, 0.33093441, 0.63820397]])

In [25]:
# will generate a random number b/w particular range
np.random.randint(1,10)

5

In [26]:
np.random.randint(1,10,6)

array([8, 6, 7, 2, 8, 3])

In [27]:
np.random.randint(1,100,(6,4))

array([[16, 47, 17, 27],
       [54, 75, 71, 20],
       [10,  9, 17, 26],
       [24, 44, 61, 22],
       [16, 71, 61, 53],
       [90, 55, 42, 83]])

In [28]:
# Indexing and Slicing of array

In [29]:
x = np.random.randint(1,50,24)

In [30]:
x

array([46, 18, 16,  8, 22, 35, 39, 20, 26, 46, 13, 39, 17, 27, 49,  6, 48,
       23, 14, 22,  5, 43,  5, 34])

In [31]:
x[0]

46

In [32]:
x[-1]

34

In [33]:
x[0:5]

array([46, 18, 16,  8, 22])

In [34]:
x

array([46, 18, 16,  8, 22, 35, 39, 20, 26, 46, 13, 39, 17, 27, 49,  6, 48,
       23, 14, 22,  5, 43,  5, 34])

In [35]:
x[0:10:2]

array([46, 16, 22, 39, 26])

In [36]:
x[::-1]

array([34,  5, 43,  5, 22, 14, 23, 48,  6, 49, 27, 17, 39, 13, 46, 26, 20,
       39, 35, 22,  8, 16, 18, 46])

In [37]:
x = np.random.randint(1,50,(4,6))

In [38]:
x

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [39]:
x[0]

array([31, 31, 16, 29,  3, 12])

In [40]:
x[0][1]

31

In [41]:
x[:,0]

array([31,  4, 22, 41])

In [42]:
x[:,0:1]

array([[31],
       [ 4],
       [22],
       [41]])

In [43]:
# 0 and 1st row, 0,1 and 2nd col
x[0:2,0:3]

array([[31, 31, 16],
       [ 4, 17, 18]])

In [44]:
x

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [45]:
x[[0,2]]

array([[31, 31, 16, 29,  3, 12],
       [22, 37, 11, 46, 15,  9]])

In [46]:
x[:, [0,2,4]]

array([[31, 16,  3],
       [ 4, 18, 19],
       [22, 11, 15],
       [41, 14, 16]])

In [50]:
x

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [51]:
x.shape

(4, 6)

In [52]:
# convers n-dimension to 1D
x.flatten()

array([31, 31, 16, 29,  3, 12,  4, 17, 18, 42, 19, 23, 22, 37, 11, 46, 15,
        9, 41, 19, 14, 45, 16, 14])

In [53]:
x = x.flatten()

In [54]:
x

array([31, 31, 16, 29,  3, 12,  4, 17, 18, 42, 19, 23, 22, 37, 11, 46, 15,
        9, 41, 19, 14, 45, 16, 14])

In [55]:
x.size

24

In [56]:
len(x)

24

In [57]:
x.reshape((4,6))

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [58]:
x.reshape((6,-1))

array([[31, 31, 16, 29],
       [ 3, 12,  4, 17],
       [18, 42, 19, 23],
       [22, 37, 11, 46],
       [15,  9, 41, 19],
       [14, 45, 16, 14]])

In [59]:
x.reshape((-1,12))

array([[31, 31, 16, 29,  3, 12,  4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9, 41, 19, 14, 45, 16, 14]])

In [60]:
np.sum(x)

534

In [62]:
x = x.reshape((4,6))

In [63]:
x

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [67]:
np.sum(x, axis=0)

array([ 98, 104,  59, 162,  53,  58])

In [66]:
np.sum(x, axis=1)

array([122, 123, 140, 149])

In [68]:
np.mean(x)

22.25

In [69]:
np.mean(x, axis=1)

array([20.33333333, 20.5       , 23.33333333, 24.83333333])

In [70]:
np.std(x)

12.390352429746837

In [71]:
np.var(x)

153.52083333333334

In [72]:
x

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14]])

In [75]:
np.hstack((x, np.array([[0],[1],[2],[3]])))

array([[31, 31, 16, 29,  3, 12,  0],
       [ 4, 17, 18, 42, 19, 23,  1],
       [22, 37, 11, 46, 15,  9,  2],
       [41, 19, 14, 45, 16, 14,  3]])

In [76]:
np.vstack((x, np.array([[1,2,3,4,5,6]])))

array([[31, 31, 16, 29,  3, 12],
       [ 4, 17, 18, 42, 19, 23],
       [22, 37, 11, 46, 15,  9],
       [41, 19, 14, 45, 16, 14],
       [ 1,  2,  3,  4,  5,  6]])